### PR TITLE
List more ciphers

### PR DESCRIPTION
**Pull request by wysman**
Add all enabled ciphers in the polarssl configuration in the available cipher_table of mongrel2

### CODE REVIEW

**Comment by wysman** [comment]
Work in progress, any help will be appreciated

**Comment by wysman** [comment]
Ok it's done

**Comment by jasom** [comment]
Just so I can wrap my brain around it here, which ciphers are still enabled that work with TLS1.1 on this?  I know there aren't any secure solutions for 1.1, but I was curious which you chose.

**Comment by jasom** [comment]
Note also that I'll do a point release after this one is merged.

**Comment by wysman** [comment]
I will do this summary this week-end

**Comment by jasom** [comment]
Thanks!

**Comment by wysman** [comment]
Ok it's done
Weak ciphers are comment to avoid to re-introduce them later, i have use ssllabs to detect them.

**Comment by jasom** [comment]
Thanks @wysman I'll rebase and pull shortly

**Comment by jasom** [comment]
Okay, if I'm reading this right, then this configuration will prefer 3DES over all other ciphers.  That seems wrong to me.

**Comment by jasom** [comment]
Ah, I am reading it wrong; the cipher_table has no effect on the ordering; we still get the order from either ssl_list_ciphers, or the configuration.

**Pull request closed without merging**
